### ISSUE TITLE
Make a paginated data model to support paginated table

### ISSUE THREAD

**Issue by ErikApption** [apption-oscode/elemental-blazor#100]
The current paginated table works great when it is bound to a list but we should figure out a model to support a backend implementation through EF and instead of assuming the backend data for a page is part of a list, we should have functions to support sorting and top queries.

Few ideas:
- Function to retrieve data for a specific page: function should include sorting criteria + page number as arguments and return a List<T> of items - but only the items for a specific page
- Function to return the total number of pages

**Comment by yjmrobert** [comment]
I like this, but we'd also have to include the number of items per page.

Would it make sense to include all these in some sort of struct instead? We could then expand on the sorting with filtering as well

**Comment by ErikApption** [comment]
What I'm thinking is not a struct but two callback functions that would replace the Dataset argument:
- List<T> LoadPage<T>(Expr<T,Object> sortingColumn, int pageNumber)
- int GetPageCount()
