### ISSUE TITLE
Dropdown Component content not aligned properly

### ISSUE THREAD

**Issue by nicksalt** [apption-oscode/elemental-blazor#129]
The content within a dropdown is not aligned properly under the label. See attached examples.

![image](https://user-images.githubusercontent.com/15818609/165826632-d869bdbf-5acc-496c-8054-77e67b48c331.png)
![image](https://user-images.githubusercontent.com/15818609/165826719-72c88772-f7ac-43e9-9491-f18441249c3f.png)

**Comment by ErikApption** [comment]
I've suggested to @yjmrobert that this one should be a good use case to integrated FAST and start with a simple component like this one
