### ISSUE TITLE
AeInputSearch icons showing out of the box...

### ISSUE THREAD

**Issue by hperezga** [apption-oscode/elemental-blazor#155]
`<AeSearchInput 
            id="search"
            SearchIconFAClass="fas fa-search"
            Placeholder=@Localizer["Search..."]
            OnInputChangeWithLastKey=@HandleSearch 
        />`
![AeInputSearchIssue_shot](https://user-images.githubusercontent.com/86124586/176011958-af230625-df7e-426f-980a-5bfa1fd5f083.png)

**Comment by yjmrobert** [comment]
Which browser and AElemental version is this?

I'm not seeing this happen on firefox or chrome on the docs

https://aelemental.z13.web.core.windows.net/components/inputs

**Comment by yjmrobert** [comment]
Viewed today, error with the css selector on the wrapper. Need to determine if it's a theming error or version mismatch
