### ISSUE TITLE
Basic Multi-Select dropdown repeats selected items 

### ISSUE THREAD

**Issue by Shashaank5** [apption-oscode/elemental-blazor#34]
Steps to reproduce
1. Select item Z in dropdown and then close dropdown
should look like this {Z}
2. open dropdown, deselect item Z and reselect item Z then close dropdown 
(doing step 2 multiple times without closing dropdown will give multiple repeats of the selection)
should look like this {Z} {Z} {Z}

**Comment by yjmrobert** [comment]
I think someone might have fixed this already as I can't reproduce this in the docs section.

Can you confirm that you can still reproduce?
