### ISSUE TITLE
Icon Sidebar

### ISSUE THREAD

**Issue by nicksalt** [apption-oscode/elemental-blazor#54]
Modify the sidebar so it doesn't expand. Similar to teams

**Comment by yjmrobert** [comment]
@dicong-Apption I think you fixed this right?


Is there a way we could have it start small by default and expand if there's children?

**Comment by dicong-Apption** [comment]
yes, I fixed it

**Comment by dicong-Apption** [comment]
should be all good now
we can reopen the issue if someone finds a bug with sidebar
