### ISSUE TITLE
Simple Table

### ISSUE THREAD

**Issue by yjmrobert** [apption-oscode/elemental-blazor#75]
Recent changes to `AeBaseTable` seems to have broken the Simple Table.

I'm not sure what a Simple Table is - this looks more like a spreadsheet? I think it should be revisited.

**Comment by yjmrobert** [comment]
@ErikApption can you clarify for me?

**Comment by ErikApption** [comment]
The idea of simple table was indeed to have a spreadsheet style table for dense datasets. Also, the style has column and row headers.

**Comment by yjmrobert** [comment]
Gotcha, thanks
________________________________
