### ISSUE TITLE
Remove virtual scrolling in AeTable

### ISSUE THREAD

**Issue by ErikApption** [apption-oscode/elemental-blazor#85]
Virtual scrolling can cause havoc in the current AeTable. AeTable should be split into two components:

- AeTable with no virtual scrolling. Size of lists should be limited
- AePaginatedTable for all large data sets

**Comment by yjmrobert** [comment]
> Size of lists should be limited

Are you thinking an exception or warning? What about defaulting to paginated table if it's bigger than `n` ?

**Comment by ErikApption** [comment]
> Are you thinking an exception or warning? What about defaulting to paginated table if it's bigger than `n` ?

Exceptions & warnings, yes definitely... prob lets say >1000 elements, it would be safe to throw a warning in the logger.
Would be nice to have a TableStyle="Default/Paginated/Auto" attribute. 

Maybe the best approach is:
1. remove virtual scrolling from AeTable
2. rename AeTable to AeSimpleTable
3. Add logic go AeTable with TableStyle to switch between implementations
