### ISSUE TITLE
AePagination has hard coded icon names

### ISSUE THREAD

**Issue by ErikApption** [apption-oscode/elemental-blazor#89]
Left arrow and right arrow are hard coded to RX icons. The arrows do not show up if these are not referenced.

**Comment by ErikApption** [comment]
Unfortunately adding RX icons to a project with Font Awesome doesn't work because they are not compatible

**Comment by Minhja101** [comment]
Replaced hard coded RX left and right arrow with RenderFragments in mn_paginatedtable.
