### ISSUE TITLE
Sorting is not working on paginated tables

### ISSUE THREAD

**Issue by ErikApption** [apption-oscode/elemental-blazor#91]
Sorting on column headers is not working the way it used to work with regular tables

**Comment by yjmrobert** [comment]
I believe @Minhja101 fixed this bug in #96 

Minh, feel free to close this when you get a chance! 🎉

**Comment by nicksalt** [comment]
@Minhja101 can we close this one? I know the paginated component needs to be updated to show the current page as the first page, but I think the sorting itself works?

**Comment by Minhja101** [comment]
On my local version it works, but I'll wait on closing it until I fix the other bugs you guys are having.
