### ISSUE TITLE
AePaginatedTable data won't update if you're on the same Page

### ISSUE THREAD

**Issue by yjmrobert** [apption-oscode/elemental-blazor#94]
If you switch the underlying data on the paginated table but you're loading the same page it won't trigger the `LoadPageItems` call.

[here](https://github.com/apption-oscode/elemental-blazor/blob/afae4c93ed60d2aba113aece0c1ed0b4615ca350/Elemental/Components/AeTable/AePaginatedTable.razor#L72)

**Comment by nicksalt** [comment]
@Minhja101 Can this one be closed?

**Comment by Minhja101** [comment]
Oh yeah, I was thinking of closing it, but I forgot!
